version: '3.8'

services:
  ubuntu22:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu22
    container_name: ubuntu22
    networks:
      - backend

  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    container_name: apache
    ports:
      - "8080:80"
    networks:
      - frontend

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile.phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
    ports:
      - "8081:80"
    networks:
      - frontend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "8082:80"
    networks:
      - frontend

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - backend
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    networks:
      - frontend
      - backend
      
networks:
  frontend:
  backend:
