FROM node:18

RUN apt-get update && \
    apt-get install -y openssh-server openjdk-17-jre && \
    mkdir /var/run/sshd

RUN ssh-keygen -A

RUN apt-get update && apt-get install -y nano

RUN useradd -m -d /home/jenkins -s /bin/bash jenkins && \
    echo "jenkins:jenkins" | chpasswd                       # change this 

RUN mkdir -p /home/jenkins && \
    chown -R jenkins:jenkins /home/jenkins

RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]