FROM jenkins/jenkins:lts

USER root

# Install useful tools
RUN apt-get update && \
    apt-get install -y lftp && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Allow Jenkins to access Docker socket
RUN groupadd -g 999 docker || true && \
    usermod -aG docker jenkins

USER jenkins